spring.application.name=cshub
spring.data.mongodb.uri=mongodb+srv://sharathchandra7060:Sharath123@clustertest.v1shdwx.mongodb.net/cshubdb?retryWrites=true&w=majority

spring.data.mongodb.auto-index-creation=true
server.port=8080
